export interface BackendAnalysisResult {
  decision_summary: string

  // Extracted ingredient names
  major_ingredients?: string[]

  // Reasoned insights generated by system + LLM
  key_insights: {
    label: "main-concern" | "worth-knowing" | "positive-note"
    text: string
  }[]

  // Responsible uncertainty statement
  uncertainty_note: string

  // System confidence level
  confidence_level: "High" | "Moderate" | "Low"
}